apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-bot-deployment
spec:
  selector:
    matchLabels:
      app: mod-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: mod-bot
    spec:
      containers:
        - name: mod-bot
          image: $(IMAGE)
          env:
            - name: ENVIRONMENT
              value: production

            - name: DISCORD_HASH
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_HASH

            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: SESSION_SECRET

            - name: DISCORD_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_PUBLIC_KEY

            - name: DISCORD_APP_ID
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_APP_ID

            - name: DISCORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_SECRET
