apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mod-bot-set
spec:
  selector:
    matchLabels:
      app: mod-bot
  serviceName: "mod-bot"
  replicas: 1
  template:
    metadata:
      labels:
        app: mod-bot
    spec:
      containers:
        - name: mod-bot
          image: $(IMAGE)
          volumeMounts:
            - mountPath: "/data"
              name: mod-bot-pvc
          env:
            - name: ENVIRONMENT
              value: production

            - name: DISCORD_HASH
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_HASH

            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: SESSION_SECRET

            - name: DISCORD_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_PUBLIC_KEY

            - name: DISCORD_APP_ID
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_APP_ID

            - name: DISCORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_SECRET

            - name: DISCORD_TEST_GUILD
              valueFrom:
                secretKeyRef:
                  name: modbot-env
                  key: DISCORD_TEST_GUILD

  volumeClaimTemplates:
    - metadata:
        name: mod-bot-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
